Drush команда для обновления данных из файла
Druki-ru/website pull request #72
Opened 2021-07-11 10:36 UTC by batkor

Этот ПР предоставляет Drush команду для импорт/обновления сущности непосредственно из файла.
Пример команды `drush druki:sync:uri docs/ru/drupal/9/routing/index.md` путь указывается относительно каталога репозитория с исходными файлами.

Например: 

Если каталог репозитория указан как `public://druki-content-source` и в команде укажите URI файла как `docs/ru/drupal/9/routing/index.md` то фактически файл должен находится по пути `public://druki-content-source/docs/ru/drupal/9/routing/index.md`

2021-07-11 10:37 UTC, batkor commented
Думаю необходимо обновлять редиректы

2021-07-12 05:17 UTC, Niklan reviewed
Спасибо, выглядит хорошо.

В будущем, конечно, лучше будет сделать иначе, но пока что и так пойдёт. 👍

---

На будущее.

В идеале наверное лучше сделать тогда команды типа:

```
drush druki-content:sync

2021-07-12 05:17 UTC, Niklan commented on web/modules/custom/druki_content/src/Commands/DrukiContentSyncCommands.php
> +   * @command druki:sync:uri
Я вот думаю, удачно ли название для команды. Учитывая что это импорт одного конкретного элемента. Плюс из трёх частей, не совсем привычно.

Может лучше придумать другой вариант названия. Например: `druki-content:sync-item`, `druki-content:sync-single-content` или `druki-content:sync-uri`.

2021-07-12 05:35 UTC, batkor commented on web/modules/custom/druki_content/src/Commands/DrukiContentSyncCommands.php
> +   * @command druki:sync:uri
я предполагал, что будут и другие команды например:
- `druki:sync:slug` - Обновление по slug ключу из фронтМаттер;
- `druki:sync:dir` - Обновление всех элементов найденных в директории.

2021-07-12 05:50 UTC, Niklan commented on web/modules/custom/druki_content/src/Commands/DrukiContentSyncCommands.php
> +   * @command druki:sync:uri
> druki:sync:slug - Обновление по slug ключу из фронтМаттер;

Не понимаю как это работать будет.

Я думаю в будущем нужно будет сделать одну команду, но с опциями для разных кейсов:

* `druki-content:sync` — для формирования очереди на основе настроек сайта.
* `--filepath` — для формирования очереди на основе одного файла (как в текущем ПР)
* `--directory` — для формирования очереди на основе директории.
* `--run-queue` — чтобы запустить очередь на обработку.

2021-07-12 05:54 UTC, batkor commented on web/modules/custom/druki_content/src/Commands/DrukiContentSyncCommands.php
> +   * @command druki:sync:uri
> Не понимаю как это работать будет.
не разбирался подробнее. но думаю можно найти файл по содержимому. например тут https://symfony.com/doc/current/components/finder.html#file-contents
> Я думаю в будущем нужно будет сделать одну команду, но с опциями для разных кейсов:
Да согласен.

2021-07-12 06:29 UTC, Niklan commented on web/modules/custom/druki_content/src/Commands/DrukiContentSyncCommands.php
> +   * @command druki:sync:uri
> не разбирался подробнее. но думаю можно найти файл по содержимому. например тут https://symfony.com/doc/current/components/finder.html#file-contents

Понял. Не знал даже о таком :)

Опять же, всё это наверное, лучше всего сделать в одной команде и решать на уровне опций, а не плодить команды для одного и того же.

Текущая норм, пока других нет, пусть будет. Но название я думаю всё же стоит сделать понятнее и проще. Как, например, такое `druki-content:sync-file` звучит логично. Синхронизируем файл и указываем путь до него.

2021-07-12 07:17 UTC, batkor commented on web/modules/custom/druki_content/src/Commands/DrukiContentSyncCommands.php
> +   * @command druki:sync:uri
Команду обновил https://github.com/Druki-ru/website/pull/72/commits/ea2d131d806b5291f59648a5b29c2d9b6054785d

2021-07-12 08:05 UTC, Niklan requested changes
Всё отлично.

Раз у нас появились команды, которые могут быть полезны, нужно добавить их в README.md проекта в раздел "Drush commands".

@batkor добавь, если есть желание, если что, я вечером сам добавлю и тогда уже смерджу.

2021-07-12 11:46 UTC, Niklan approved these changes

2021-07-12 11:46 UTC, merged